# PANDAS-III

In [2]:
import pandas as pd
import numpy as np

In [3]:
titanic_dataset_url = "https://raw.githubusercontent.com/datasciencedojo/datasets/refs/heads/master/titanic.csv"

df = pd.read_csv(titanic_dataset_url)

In [5]:
df['Name'].str.replace("Mr", "Sir", regex=False).head()

0                             Braund, Sir. Owen Harris
1    Cumings, Sirs. John Bradley (Florence Briggs T...
2                               Heikkinen, Miss. Laina
3        Futrelle, Sirs. Jacques Heath (Lily May Peel)
4                            Allen, Sir. William Henry
Name: Name, dtype: str

In [6]:
df['Name'].head()

0                              Braund, Mr. Owen Harris
1    Cumings, Mrs. John Bradley (Florence Briggs Th...
2                               Heikkinen, Miss. Laina
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                             Allen, Mr. William Henry
Name: Name, dtype: str

In [8]:
df.loc[1]['Name']

'Cumings, Mrs. John Bradley (Florence Briggs Thayer)'

In [9]:
df.loc[1, 'Name']

'Cumings, Mrs. John Bradley (Florence Briggs Thayer)'

In [15]:
start = df.loc[1, 'Name'].find("(")

In [16]:
end = df.loc[1, 'Name'].find(")")

In [20]:
df.loc[1, 'Name'][0:start] + df.loc[1, 'Name'][end:-1]

'Cumings, Mrs. John Bradley '

In [23]:
def remove_substring(name):
    start = name.find("(")
    end = name.find(")")
    new_name = name[:start] + name[end:-1]
    new_name = new_name.strip()
    return new_name

In [24]:
remove_substring(df.loc[1, 'Name'])

'Cumings, Mrs. John Bradley'

In [ ]:
df['Name_trimed'] = df['Name'].apply(remove_substring)

In [26]:
df['Name_trimed']

0                       Braund, Mr. Owen Harri
1                   Cumings, Mrs. John Bradley
2                        Heikkinen, Miss. Lain
3                 Futrelle, Mrs. Jacques Heath
4                      Allen, Mr. William Henr
                        ...
886                       Montvila, Rev. Juoza
887                Graham, Miss. Margaret Edit
888    Johnston, Miss. Catherine Helen "Carrie
889                       Behr, Mr. Karl Howel
890                         Dooley, Mr. Patric
Name: Name_trimed, Length: 891, dtype: str

# Replace Substring with regex

In [29]:
# * - zero or more
# . match any charecter

df['Name'].str.replace(r"\(.*\)", "HELLO", regex=True).head()

0               Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley HELLO
2                Heikkinen, Miss. Laina
3    Futrelle, Mrs. Jacques Heath HELLO
4              Allen, Mr. William Henry
Name: Name, dtype: str

In [30]:
import re

def is_valid_email(email):
    """
    Validates an email address using a regular expression.

    Args:
        email (str): The email address to validate.

    Returns:
        bool: True if the email is valid, False otherwise.
    """
    # Simple regex pattern for most common email formats:
    # ^[a-zA-Z0-9._%+-]+ : Matches the username part (starts with alphanumeric, allows specific special chars)
    # @ : Matches the mandatory @ symbol
    # [a-zA-Z0-9.-]+ : Matches the domain name part (allows alphanumeric, dots, hyphens)
    # \\. : Matches a literal dot (.)
    # [a-zA-Z]{2,} : Matches the top-level domain (e.g., .com, .org), at least two letters long
    # $ : Asserts the end of the string
    pattern = r'^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'
    
    # Use re.fullmatch to ensure the entire string matches the pattern
    if re.fullmatch(pattern, email):
        return True
    else:
        return False

# Example Usage
test_emails = [
    "test@example.com",
    "name.surname@gmail.com",
    "anonymous123@yahoo.co.uk",
    "invalid-email.com",
    "user@.com",
    "user@@example.com"
]

for email in test_emails:
    if is_valid_email(email):
        print(f"'{email}' is a valid email address.")
    else:
        print(f"'{email}' is an invalid email address.")

'test@example.com' is a valid email address.
'name.surname@gmail.com' is a valid email address.
'anonymous123@yahoo.co.uk' is a valid email address.
'invalid-email.com' is an invalid email address.
'user@.com' is an invalid email address.
'user@@example.com' is an invalid email address.

# Split and Access Elemts

In [32]:
df['Name'][0]

'Braund, Mr. Owen Harris'

In [33]:
df['Name'].str.split(",")[0]

['Braund', ' Mr. Owen Harris']

In [34]:
df['Name'].str.split()[0]

['Braund,', 'Mr.', 'Owen', 'Harris']

In [35]:
df['Name'].str.split().str[0]

0         Braund,
1        Cumings,
2      Heikkinen,
3       Futrelle,
4          Allen,
          ...
886     Montvila,
887       Graham,
888     Johnston,
889         Behr,
890       Dooley,
Name: Name, Length: 891, dtype: object

# Strip Spaces

In [37]:
df['Name'].str.strip()

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: str

In [38]:
df['Name'].str.rstrip()

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: str

# Find Position of Substring

In [42]:
df['Name'].str.find("Mr")

0       8
1       9
2      -1
3      10
4       7
       ..
886    -1
887    -1
888    -1
889     6
890     8
Name: Name, Length: 891, dtype: int64

In [45]:
count = df['Name'].str.contains("Miss").sum()
print(f"Number of Miss: {count}")

Number of Miss: 182

In [46]:
data = {
    'Name': [
        'John Doe', 'Jane Smith', 'Emily Johnson',
        'Robert Brown', 'Anna-Marie Lee'
    ],
    'Email': [
        'john@example.com', 'jane.smith@work.org',
        'emily_j@data.net', 'robertb@yahoo.com',
        'anna.lee@company.co'
    ]
}

df = pd.DataFrame(data)

In [49]:
df

             Name                Email
0        John Doe     john@example.com
1      Jane Smith  jane.smith@work.org
2   Emily Johnson     emily_j@data.net
3    Robert Brown    robertb@yahoo.com
4  Anna-Marie Lee  anna.lee@company.co

In [50]:
df['Name'].str.pad(width=20, side='left', fillchar='-')

0    ------------John Doe
1    ----------Jane Smith
2    -------Emily Johnson
3    --------Robert Brown
4    ------Anna-Marie Lee
Name: Name, dtype: str

# Categorical Data in Pandas

In [53]:
class_data = {
    'Name': ['A', 'B', 'C', 'D'],
     'Groups': ['G1', 'G2', 'G3', 'G4']        
}

In [54]:
class_df = pd.DataFrame(class_data)
class_df

  Name Groups
0    A     G1
1    B     G2
2    C     G3
3    D     G4

In [56]:
class_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      str
 1   Groups  4 non-null      str
dtypes: str(2)
memory usage: 196.0 bytes

In [ ]:
class_df['Group_cat'] = pd.Categorical(
    class_df['Groups'],
    categories=['G3', 'G1', 'G2', 'G4'], # Ascending order
    ordered=True
)

In [58]:
class_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Name       4 non-null      str
 1   Groups     4 non-null      str
 2   Group_cat  4 non-null      category
dtypes: category(1), str(2)
memory usage: 404.0 bytes

In [59]:
class_df['Group_cat'].cat.categories

Index(['G3', 'G1', 'G2', 'G4'], dtype='str')

In [61]:
class_df['Group_cat'] >= 'G4'

0    False
1    False
2    False
3     True
Name: Group_cat, dtype: bool

In [64]:
class_df['Group_cat'] >= 'G1'

0     True
1     True
2    False
3     True
Name: Group_cat, dtype: bool

In [65]:
df = pd.read_csv(titanic_dataset_url)

In [66]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

In [67]:
df['Embarked'].unique()

<StringArray>
['S', 'C', 'Q', nan]
Length: 4, dtype: str

In [68]:
df['Embarked'] = df['Embarked'].fillna("N")

In [69]:
df['Embarked'].unique()

<StringArray>
['S', 'C', 'Q', 'N']
Length: 4, dtype: str

In [70]:
df['Embarked_auto_cat'] = df['Embarked'].astype('category')

In [71]:
df['Embarked_auto_cat'].cat.categories

Index(['C', 'N', 'Q', 'S'], dtype='str')

In [72]:
df['Embarked_cust_cat'] = pd.Categorical(
    df['Embarked'],
    categories=['N', 'S', 'C', 'Q'], # Ascending order
    ordered=True
)

In [73]:
df['Embarked_cust_cat'].cat.categories

Index(['N', 'S', 'C', 'Q'], dtype='str')

In [76]:
df['Embarked_cust_cat'].head()

0    S
1    C
2    S
3    S
4    S
Name: Embarked_cust_cat, dtype: category
Categories (4, str): ['N' < 'S' < 'C' < 'Q']

In [75]:
df['Embarked_cust_cat'].cat.codes.head()

0    1
1    2
2    1
3    1
4    1
dtype: int8

In [77]:
df['Sex'].unique()

<StringArray>
['male', 'female']
Length: 2, dtype: str

In [ ]:
df['Sex_cat_custom'] = df["Sex"].apply(lambda sex: 1 if sex == 'male' else 0)

In [ ]:
df[['Sex','Sex_cat_custom']]

# Date Functionality in Pandas

In [27]:
df = pd.DataFrame({
    'event': ['Concert', 'Conference', 'Wedding'],
    'date': ['2025-01-01', '2025-03-15', '2025-07-20']
})

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   event   3 non-null      str
 1   date    3 non-null      str
dtypes: str(2)
memory usage: 180.0 bytes

In [28]:
df['date_pandas'] = pd.to_datetime(df['date'])

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   event        3 non-null      str
 1   date         3 non-null      str
 2   date_pandas  3 non-null      datetime64[us]
dtypes: datetime64[us](1), str(2)
memory usage: 204.0 bytes

In [10]:
df

        event        date date_pandas
0     Concert  2025-01-01  2025-01-01
1  Conference  2025-03-15  2025-03-15
2     Wedding  2025-07-20  2025-07-20

In [11]:
df['date_pandas'].dt.year

0    2025
1    2025
2    2025
Name: date_pandas, dtype: int32

In [12]:
df['date_pandas'].dt.month

0    1
1    3
2    7
Name: date_pandas, dtype: int32

In [13]:
df['date_pandas'].dt.day

0     1
1    15
2    20
Name: date_pandas, dtype: int32

In [14]:
df['date_pandas'].dt.weekday

0    2
1    5
2    6
Name: date_pandas, dtype: int32

In [17]:
df['date_pandas'].dt.day_name()

0    Wednesday
1     Saturday
2       Sunday
Name: date_pandas, dtype: str

In [18]:
df[df['date_pandas'] > '2025-04-01']

     event        date date_pandas
2  Wedding  2025-07-20  2025-07-20

In [19]:
df[df['date_pandas'].between('2025-01-01', '2025-06-01')]

        event        date date_pandas
0     Concert  2025-01-01  2025-01-01
1  Conference  2025-03-15  2025-03-15

# Creating Datetime Ranges
 other frequenct
    . M --> month end
    . MS --> month start
    . W --> weekly
    . H, T, S --> hour, minute, second

In [23]:
pd.date_range(start='2026-02-01', end='2026-02-10', freq='D')

DatetimeIndex(['2026-02-01', '2026-02-02', '2026-02-03', '2026-02-04',
               '2026-02-05', '2026-02-06', '2026-02-07', '2026-02-08',
               '2026-02-09', '2026-02-10'],
              dtype='datetime64[us]', freq='D')

In [24]:
pd.date_range(start='2024-01-31', end='2024-03-01', freq='ME')

DatetimeIndex(['2024-01-31', '2024-02-29'], dtype='datetime64[us]', freq='ME')

In [25]:
pd.date_range(start='2024-01-01', end='2024-03-10', freq='MS')

DatetimeIndex(['2024-01-01', '2024-02-01', '2024-03-01'], dtype='datetime64[us]', freq='MS')

# Date Arithmatic

In [29]:
df['next_week'] = df['date_pandas'] + pd.Timedelta(days=7)

In [30]:
df

        event        date date_pandas  next_week
0     Concert  2025-01-01  2025-01-01 2025-01-08
1  Conference  2025-03-15  2025-03-15 2025-03-22
2     Wedding  2025-07-20  2025-07-20 2025-07-27

In [31]:
df['days_to_event'] = df['date_pandas'] - pd.Timestamp.today()

In [32]:
df

        event        date date_pandas  next_week              days_to_event
0     Concert  2025-01-01  2025-01-01 2025-01-08 -425 days +23:58:03.324827
1  Conference  2025-03-15  2025-03-15 2025-03-22 -352 days +23:58:03.324827
2     Wedding  2025-07-20  2025-07-20 2025-07-27 -225 days +23:58:03.324827

# PANDAS COMPLETED